# Procedures

We will recruit 100 young adults (ages 18-26) with a self-reported history of an ED and/or current subclinical ED cognitions or behaviors to take part in an intervention to support ED recovery. Participants will be randomized to the Body Project (n = 50) or BAM (n = 50). Participants in both groups will complete four weekly, peer-led, 1-hour sessions, and complete assessments baseline, post-intervention, and at 1-month and 6-month follow-up. We will collect both self-report and behavioral assessments of fear of fatness to test the hypothesis that BAM effectively targets this symptom. 

**Recruitment:**  Identified avenues for recruitment include: (1) University Health Services at UW-Madison and other area colleges and universities (2) flyers at area businesses (e.g. fitness centers, coffee shops) (3) online advertisement on social media platforms (4) direct, peer-to-peer recruitment by peer facilitators (5) identification of eligible individuals with a diagnosis of an ED that is ‘in partial recovery’ or ‘in full recovery’ with upcoming appointments in the UW-Health system through the UW-Health Institute for Clinical and Translational Research (estimated n ~ 30 eligible individuals/month across clinics) and (6) campus e-mail recruitment


