# Self-Report Measures

Self-report measures are scored via the `scorekeeper` R package, and scoresheets for all measures are available [here](https://github.com/embark-lab/bam-scorekeep/tree/main/scoresheets). You can replicate scoring procedures for a given measure by runnning the scorekeep function with raw data that matches charachteristics of the raw data outlined in each scoresheet. Below is information on measures included in this project and soring procedures employed. 

## Childhood Trauma Questionnaire
The Childhood Trauma Questionnaire (CTQ) is a standardized self-report inventory that measures the severity of childhood trauma and participants’ tendency to underreport maltreatment, and has been validated in both clinical and non-clinical populations [@bernsteinValidityChildhoodTrauma1997; @villanoPsychometricUtilityChildhood2004]. The CTQ is a retrospective 28-item self-report inventory that measures the severity of different types of childhood trauma, producing five clinical subscales each comprised of five items: Emotional Abuse, Physical Abuse, Sexual Abuse, Emotional Neglect, Physical Neglect. The measure also includes a three-item Minimization/Denial scale indicating the potential underreporting of maltreatment. Participants respond to each item in the context of “when you were growing up” and answer according to a five-point Likert scale ranging from “never” = 1 to “very often” = 5, producing scores of 5 to 25 for each trauma subscale. The three items comprising the Minimization/Denial scale are dichotomized (“never” = 0, all other responses = 1) and summed; a total of one (1) or greater suggests the possible underreporting of maltreatment (false negatives).

### Scoring 
Scoring for the CTQ includes: 

1. Renaming variables with descriptive names

2. Creating sum scores for each subscale (5 items for each of the 5 subscales)

3. Dichotomizing items for the minimization scale

4. Summing dichotimized items to create the minimization score

### Key Variables
Key summary variables from the CTQ include: 
`ctq_emo_abuse_complete` (CTQ emotional abuse subscale sum - completers only)
`ctq_emo_abuse_NAs` (number of NA items in the subscale)
`ctq_emo_abuse_weighted_sum` (CTQ weighted sum of scores contributing to the emotional abuse subscale)

`ctq_phys_abuse_complete` (CTQ pysical abuse subscale sum - completers only)
`ctq_phys_abuse_NAs` (number of NA items in the subscale)
`ctq_phys_abuse_weighted_sum` (CTQ weighted sum of scores contributing to the emotional abuse subscale)

`ctq_sex_abuse_complete` (CTQ sexual abuse subscale sum - completers only)
`ctq_sex_abuse_NAs` (number of NA items in the subscale)
`ctq_sex_abuse_weighted_sum` (CTQ weighted sum of scores contributing to the sexual abuse subscale)

`ctq_emo_neglect_complete`(CTQ emotional neglect subscale sum - completers only)
`ctq_emo_neglect_NAs` (number of NA items in the subscale)
`ctq_emo_neglect_weighted_sum` (CTQ weighted sum of scores contributing to the emotional neglect subscale)

`ctq_phys_neglect_complete`(CTQ physical neglect subscale sum - completers only)
`ctq_phys_neglect_NAs` (number of NA items in the subscale)
`ctq_phys_neglect_weighted_sum` (CTQ weighted sum of scores contributing to the emotional neglect subscale)

`ctq_minimize` (CTQ minimization score - completers only)

## Demographics
### Scoring 
### Key Variables

## ED History Questionnaire
### Scoring 
### Key Variables

## ED100k
### Scoring 
### Key Variables

## ED Fear Questionnaire
### Scoring 
### Key Variables


## Eating Pathology Symptom Inventory 

We used the 45-item Eating Pathology Symptom Inventory (EPSI; [@forbushDevelopmentValidationEating2013]) to assess eating disorder symptoms at pre-intervention, post-intervention, and 8-week follow-up. The EPSI has been validated in clinical, college, and community samples, with 7-8 subscales in various populations, with the 8-subscale version being the most commonly-employed version of the measure [@coniglioFactorialIntegrityValidation2018]. The 8 subscales includ: Body Dissatisfaction, Binge Eating, Cognitive Restraint, Purging, Restricting, Excessive Exercise, Negative Attitudes toward Obesity, and Muscle Building. Each item is scored on a 5-point Likert-style scale (0 = Never; 4= Often) to describe how well each item describes the participant experiences. Scores are derived by summing responses across the questions included in each subscale.

### Scoring
To clean the data, the scoresheet:

1) selects only the variables that are relevant for the current measure

2) rename raw variables to appropraite names that are easy to understand

3) creates eight additional variables based on sum scores reflecting eight subscales of the questionnaire: Body Dissatisfaction, Binge Eating, Cognitive Restraint, Purging, Restricting, Excessive Exercise, Negative Attitudes toward Obesity, and Muscle Building

4) select only a few columns that will go into the final dataset

### Key Variables
The variables below are sum of different subscales. **Sum variables exclude those who did not complete all items of a subscale**

`epsi_body_dissatisfaction` (reflects participant's body dissatisfaction symptoms)

`epsi_binge_eating` (reflects participant's binge eating symptoms)

`epsi_cognitive_restraint` (reflects participant's cognitive restraint symptoms)

`epsi_purging` (reflects participant's purging symptoms)

`epsi_restricting` (reflects participant's restricting symptoms)

`epsi_excessive_exercise` (reflects participant's excessive exercise symptoms)

`epsi_negative_attitude` (reflects participant's negative attidtude towards obesity symptoms)

`epsi_muscle_building` (reflects participant's muscle building symptoms)

## Fat Phobia Scale - Short Form 

The shortened Fat Phobia Scale (FPS)  utilizes 14 questions to assess fatphobia (from the 50-item original scale). It is intended to measure fat phobia levels in the tested population through various personality traits and whether there is bias when people apply them to an overweight person (@baconFatPhobiaScale2001). The shortened FPS questionnaire demonstrates high reliability when compared to the original 50 question scale. The FPS uses a 5-point sliding scale with 1 being equal to a different negative descriptive variable for each respective question and 5 being equal to a different positive variable for each respective question. Some items are reverse scored prior to data aggregation such that th 1 (negative) to 5 (positive) valuation is maintained across the scale.

### Scoring
In order to clean the data, the scoresheet:

1. Selects and renames variables to include descriptive terms from questions in the scale
2. Codes all items such that the negative descriptor is labeled as 1 and the positive descriptor is labeled as 5
3. Computes a mean score using all 14-items 

### Key Variables
`fps_mean` (average of scores in response to questions asking how different negative and positive descriptors should be applied to a fat person)


## Food Security Questionnaire
### Scoring 
### Key Variables

## GAD-7
### Scoring 
### Key Variables


## Goldfarb Fear of Fat Scale
### Scoring 
### Key Variables

## Ideal Body Stereotype Scale - Revised
### Scoring 
### Key Variables

## PHQ-9
### Scoring 
### Key Variables

## Sociocultural Attitudes Towards Appearance Questionnaire
### Scoring 
### Key Variables

## Traditional Masculinity-Femininity Scale
### Scoring 
### Key Variables

## Universal Measure of Bias - Fat
### Scoring 
### Key Variables

## Weight and Dieting History Questionnaire
### Scoring 
### Key Variables
