# Task-based Measures

## Implicit Association Test - Weight
The Weight-IAT is a validated measure of automatic, unconscious attitudes that has previously been used to evaluate implicit weight-related biases [ @phelanImplicitExplicitWeight2014] The Weight-IAT compares the accuracy of, and time required to categorize images of larger-bodied and thinner people together with positively- and negatively-valanced words. Outcomes include reaction time and percentage of correct categorizations.

### Scoring 
The IAT scoring algorithm involves several steps, with a rigorous scoring procedure involving 12 specifications [@greenwaldUnderstandingUsingImplicit2003]

Steps include:

1. Using data from Blocks 3,4,6, and 7

2. Eliminate trials with latencies > 10,000 ms; eliminate subjects for whom more than 10% of trials have latency less than 300 ms

3. Use all remaining trials

4. No extreme-value treatment (beyond Step 2)

5. Compute mean of correct latencies for each block

6. Compute one pooled SD for all trials in blocks 3 & 6; another for blocks 4 & 7

7. Replace each error latency with block mean (computed in Step 5) + 600 ms

8. No transformation 

9. Average the resulting values for each of the four blocks

10. Compute two differences: B6 - B3 and B7 - B4

11. Divide each difference by its associated pooled- trials SD from Step 6

12. Average the two quotients from Step 11

R code for cleaning IAT data prior to implementing the scoring algorithm is available [here]().
R code for completing the scoring algorithm with cleaned data is available [here]()

### Key Variables

## Weight Based Approach Avoidance Task
An interactive task will manipulate congruency between reward- and threat-related outcomes. Participants learn, through trial-and-error, which of three responses, indicated as geometric shapes, to select to achieve a particular outcome. Critically, each response option is associated with a probability of both a reward outcome (points) and an additional outcome (i.e., images of body parts of those in larger bodies). The response-outcome contingencies (e.g., which option is most likely to lead to reward) switch throughout the task, such that half the time the option that is most likely to lead to reward is also most likely to lead to seeing large body images, and half the time the highest reward option is least likely to lead to seeing large body images. Participants are instructed to earn as many points as possible (reward goals), allowing us to test biases in decision-making when large body images are likely. 

### Scoring 
### Key Variables
