--- 
title: "Body Advocacy Movement - Study Procedures and Measures"
author: "Katherine Schaumberg"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
keep_md: true
bibliography: ['BAM-bookdown.bib']
csl: apa-single-spaced.csl
link-citations: true
github-repo: embark-lab/bam-bookdown
description: "This is a package which contains study information, measures, and complete data dictionary for the Body Advocacy Movement Study (Wave 1: 2020-2022)"
---



<!--chapter:end:index.Rmd-->

# Study Premise

The Body Advocacy Movement Study (Phase 1: 2021-2023) is a pilot study investigating the feasiblility, acceptability, and preliminary efficacy of an eating disorder risk reduction intervention developed by the EMBARK lab in 2020.  

While existing, dissonance programs (i.e. the Body Project) target reductions in thin-ideal internalization, fears related to fatness and weight gain may be a particularly salient cognitive target among those with current or past eating disorder symptomatology [@levinsonAddressingFearFat2014]. In an effort to mitigate risk for ED onset and relapse among high-risk young adults (i.e. those in ED partial- or full-remission and/or those with ongoing subthreshold ED symptoms), the current project includes development and initial evaluation of a novel, peer-led intervention that focuses specifically on fear of fatness and anti-fat bias (the Body Advocacy Movement; BAM). 

This project aims to recruit 60 young adults (ages 18-26) -- randomized to a standard dissonance intervention program (the Body Project; N = 20) or BAM (N = 40). Our objective is to examine the degree to which BAM can reduce fear of fatness and weight gain along with internalized anti-fat bias and reduce risk for ED symptom exacerbation and promote ongoing ED recovery in a high-risk, young adult sample. We will evaluate feasibility and acceptability of BAM and estimate effects of the intervention on self-report and behavioral measures of fear of weight gain and fatness, anti-fat bias, and eating disorder symptoms. We will conduct initial effect size comparisons with the Body Project to determine whether BAM shows potency in specifically targeting fear of fatness and anti-fat bias.

## Specific Aims

**Aim 1**: Examine the acceptability and feasibility of BAM in a high-risk young adult sample. Acceptability: Acceptability will be assessed via attrition across a 4-session intervention along with qualitative feedback from a brief survey at post-intervention. We expect to meet benchmarks of high acceptability (average ratings of > 4 [out of 5] on post-intervention survey; < 20% attrition). Feasibility: Feasibility will be benchmarked via intervention adherence (average competency > 8.0 on 0-10 scale) and recruitment goals. 

**Aim 2**: Estimate the effects of the intervention on fear of fatness, anti-fat bias, and eating disorder symptoms. We hypothesize that the BAM intervention will result in acute reductions (post-intervention) in fatphobia and anti-fat bias across self—report and behavioral measures, outperforming the Body Project on targets related to anti-fat bias, specifically.



<!--chapter:end:01-Study-Premise.Rmd-->

# Procedures

Individuals are recruited to BAM via ....xxx


<!--chapter:end:02-Procedures.Rmd-->

# Interventions

## The Body Project

## The Body Advocacy Movement


<!--chapter:end:03-Interventions.Rmd-->

# Self-Report Measures


<!--chapter:end:04-SR-Measures.Rmd-->

# Task-based Measures

here are some task based measures

<!--chapter:end:05-Task-Measures.Rmd-->

# Sample Description

Individduals were recruited to the Body Advocacy Movement through a student organizaiton developed simultanously at the University of Wisconsin - Madison



<!--chapter:end:06-Sample-Description.Rmd-->

# Data Requests 

<!--chapter:end:07-Data-Requests.Rmd-->


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```


`r if (knitr:::is_html_output()) '
# References {-}
'`

<!--chapter:end:08-References.Rmd-->

